### ISSUE TITLE
BMI can't be disabled

### ISSUE THREAD

**Issue by woj-tek** [oliexdev/openScale#226] opened 2018-03-11 14:41 UTC
As the title says - BMI calculation and display can't be disabled (and thus hidden in the overview graph; somewhat related to  #130).

**Comment by momo42** [comment] 2018-03-13 23:29
I use this app almost every day and I really like how it evolved over time but I just monitor my weight. So I disabled all the other graphs. In the recent version disabling the BMI is not possible. In the graph section this is not a big deal because you can disable it here "on the fly" but the overview graph degenerates to two straight lines in my case ... the bmi on the bottom and the weight on the top. I'd really like to have the option to hide the bmi graph. :-)

**Comment by erijo** [comment] 2018-03-18 12:10
I'm working on restructuring the preferences a bit. This will be included in that work.

**Closed** 2018-03-24 07:37 UTC
Labels: enhancement

**Comment by erijo** [comment] 2018-03-24 15:03
Please test the latest dev build and let me know what you think about the new preferences and if you have any suggestion.

https://github.com/oliexdev/openScale/releases/tag/travis-dev-build

**Comment by woj-tek** [comment] 2018-03-24 16:59
It looks great now (very very! and I love the new weight input box!)

There is a slight issue with the settings - sometimes tapping on the category (left part, with the name) doesn't open the new screen - at first I thought it was linked to the toggle (right part) but it's possible to navigate to the next screen with toggle off. Works always with circumference. 

Also (possibly related with above) - it's possible to disable metric and enable it in overview screen.

**Comment by erijo** [comment] 2018-03-24 18:49
Hmm. You're not supposed to be able to navigate to the next screen when the switch is off. Can you provide step-by-step instructions on how to reproduce this?

**Comment by erijo** [comment] 2018-03-24 18:57
Think I might have found the bug. Please test with latest dev version once 57daf44 has been built.

**Comment by woj-tek** [comment] 2018-03-26 15:58
OK, it seems to work ok now. Thank you for the quick fix
