### ISSUE TITLE
Crash while clicking around in graph

### ISSUE THREAD

**Issue by erijo** [oliexdev/openScale#202] opened 2018-02-24 08:55 UTC
Got the following crash while clicking around in the graph with regression line active (degree 10). Don't have time just now to figure out exactly what I did, but perhaps it can be fixed anyway.

Build version: 1.7-dev_0cba7961 
Current date: 2018-02-24 09:53:51 
Device: LGE Nexus 5X 
 
Stack trace:  
java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
	at com.health.openscale.core.utils.PolynomialFitter.gj_swap(PolynomialFitter.java:186)
	at com.health.openscale.core.utils.PolynomialFitter.gj_echelonize(PolynomialFitter.java:156)
	at com.health.openscale.core.utils.PolynomialFitter.getBestFit(PolynomialFitter.java:118)
	at com.health.openscale.gui.fragments.GraphFragment.generateLineData(GraphFragment.java:425)
	at com.health.openscale.gui.fragments.GraphFragment.generateGraphs(GraphFragment.java:526)
	at com.health.openscale.gui.fragments.GraphFragment.access$700(GraphFragment.java:73)
	at com.health.openscale.gui.fragments.GraphFragment$2.onClick(GraphFragment.java:158)
	at android.view.View.performClick(View.java:6294)
	at android.view.View$PerformClick.run(View.java:24770)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

User actions: 
2018-02-24 09:05:18: MainActivity resumed
2018-02-24 09:05:31: MainActivity paused
2018-02-24 09:05:36: MainActivity resumed
2018-02-24 09:05:43: MainActivity paused
2018-02-24 09:05:51: MainActivity resumed
2018-02-24 09:06:10: MainActivity paused
2018-02-24 09:06:10: DataEntryActivity created
2018-02-24 09:06:11: DataEntryActivity resumed
2018-02-24 09:06:24: DataEntryActivity paused
2018-02-24 09:06:47: DataEntryActivity resumed
2018-02-24 09:07:02: DataEntryActivity paused
2018-02-24 09:48:27: DataEntryActivity resumed
2018-02-24 09:48:29: DataEntryActivity paused
2018-02-24 09:48:29: MainActivity resumed
2018-02-24 09:48:30: DataEntryActivity destroyed
2018-02-24 09:48:31: MainActivity paused
2018-02-24 09:48:31: SettingsActivity created
2018-02-24 09:48:31: SettingsActivity resumed
2018-02-24 09:51:07: SettingsActivity paused
2018-02-24 09:51:07: MainActivity destroyed
2018-02-24 09:51:07: MainActivity created
2018-02-24 09:51:07: MainActivity resumed
2018-02-24 09:51:08: SettingsActivity destroyed

**Comment by erijo** [comment] 2018-02-24 11:09
The crash happens with both week and month view unchecked and the going from 2018 to 2017 with the following data:

"bone","comment","dateTime","fat","hip","lbw","muscle","waist","water","weight"
0.0,"","13.12.2018 13:20",19.3,0.0,0.0,42.5,0.0,59.4,85.2
0.0,"","13.12.2018 13:19",19.3,0.0,0.0,42.5,0.0,59.4,85.2
0.0,"","13.12.2018 13:18",19.3,0.0,0.0,42.5,0.0,59.4,85.2
0.0,"","13.12.2018 13:17",19.3,0.0,0.0,42.5,0.0,59.4,85.2
0.0,"","13.12.2018 13:16",19.3,0.0,0.0,42.5,0.0,59.4,85.2
0.0,"","09.12.2018 19:40",20.3,0.0,0.0,42.2,0.0,58.7,86.9
0.0,"","09.12.2018 19:39",20.3,0.0,0.0,42.2,0.0,58.7,86.9
0.0,"","09.12.2018 19:38",20.3,0.0,0.0,42.2,0.0,58.7,86.9
0.0,"","09.12.2018 19:37",20.3,0.0,0.0,42.2,0.0,58.7,86.9
0.0,"","09.12.2018 19:36",20.3,0.0,0.0,42.2,0.0,58.7,86.9
0.0,"","08.12.2018 20:32",19.9,0.0,0.0,42.2,0.0,59.0,86.8
0.0,"","08.12.2018 20:31",19.9,0.0,0.0,42.2,0.0,59.0,86.8
0.0,"","08.12.2018 20:30",19.9,0.0,0.0,42.2,0.0,59.0,86.8
0.0,"","08.12.2018 20:29",19.9,0.0,0.0,42.2,0.0,59.0,86.8
0.0,"","08.12.2018 20:28",19.9,0.0,0.0,42.2,0.0,59.0,86.8
0.0,"","05.12.2018 18:25",20.3,0.0,0.0,42.2,0.0,58.7,86.7
0.0,"","05.12.2018 18:24",20.3,0.0,0.0,42.2,0.0,58.7,86.7
0.0,"","05.12.2018 18:23",20.3,0.0,0.0,42.2,0.0,58.7,86.7
0.0,"","05.12.2018 18:22",20.3,0.0,0.0,42.2,0.0,58.7,86.7
0.0,"","05.12.2018 18:21",20.3,0.0,0.0,42.2,0.0,58.7,86.7
0.0,"","04.08.2018 08:12",21.2,0.0,0.0,41.5,0.0,58.0,89.7
0.0,"","04.08.2018 08:11",21.2,0.0,0.0,41.5,0.0,58.0,89.7
0.0,"","04.08.2018 08:10",21.2,0.0,0.0,41.5,0.0,58.0,89.7
0.0,"","04.08.2018 08:09",21.2,0.0,0.0,41.5,0.0,58.0,89.7
0.0,"","04.08.2018 08:08",21.2,0.0,0.0,41.5,0.0,58.0,89.7
0.0,"","03.08.2018 05:21",26.4,0.0,0.0,41.6,0.0,54.6,89.0
0.0,"","03.08.2018 05:20",26.4,0.0,0.0,41.6,0.0,54.6,89.0
0.0,"","03.08.2018 05:19",26.4,0.0,0.0,41.6,0.0,54.6,89.0
0.0,"","03.08.2018 05:18",26.4,0.0,0.0,41.6,0.0,54.6,89.0
0.0,"","03.08.2018 05:17",26.4,0.0,0.0,41.6,0.0,54.6,89.0
0.0,"","02.08.2018 07:36",25.0,0.0,0.0,41.7,0.0,55.6,88.8
0.0,"","02.08.2018 07:35",25.0,0.0,0.0,41.7,0.0,55.6,88.8
0.0,"","02.08.2018 07:34",25.0,0.0,0.0,41.7,0.0,55.6,88.8
0.0,"","02.08.2018 07:33",25.0,0.0,0.0,41.7,0.0,55.6,88.8
0.0,"","02.08.2018 07:32",25.0,0.0,0.0,41.7,0.0,55.6,88.8
0.0,"","31.07.2018 04:43",29.2,0.0,0.0,41.6,0.0,52.8,89.1
0.0,"","31.07.2018 04:42",29.2,0.0,0.0,41.6,0.0,52.8,89.1
0.0,"","31.07.2018 04:41",29.2,0.0,0.0,41.6,0.0,52.8,89.1
0.0,"","31.07.2018 04:40",29.2,0.0,0.0,41.6,0.0,52.8,89.1
0.0,"","31.07.2018 04:39",29.2,0.0,0.0,41.6,0.0,52.8,89.1
0.0,"","18.07.2018 07:58",22.1,0.0,0.0,41.2,0.0,57.4,91.3
0.0,"","18.07.2018 07:57",22.1,0.0,0.0,41.2,0.0,57.4,91.3
0.0,"","18.07.2018 07:56",22.1,0.0,0.0,41.2,0.0,57.4,91.3
0.0,"","18.07.2018 07:55",22.1,0.0,0.0,41.2,0.0,57.4,91.3
0.0,"","18.07.2018 07:54",22.1,0.0,0.0,41.2,0.0,57.4,91.3
0.0,"","12.07.2018 07:18",21.9,0.0,0.0,41.3,0.0,57.6,91.1
0.0,"","12.07.2018 07:17",21.9,0.0,0.0,41.3,0.0,57.6,91.1
0.0,"","12.07.2018 07:16",21.9,0.0,0.0,41.3,0.0,57.6,91.1
0.0,"","12.07.2018 07:15",21.9,0.0,0.0,41.3,0.0,57.6,91.1
0.0,"","12.07.2018 07:14",21.9,0.0,0.0,41.3,0.0,57.6,91.1
0.0,"","16.06.2018 05:20",25.3,0.0,0.0,41.5,0.0,55.4,89.5
0.0,"","16.06.2018 05:19",25.3,0.0,0.0,41.5,0.0,55.4,89.5
0.0,"","16.06.2018 05:18",25.3,0.0,0.0,41.5,0.0,55.4,89.5
0.0,"","16.06.2018 05:17",25.3,0.0,0.0,41.5,0.0,55.4,89.5
0.0,"","16.06.2018 05:16",25.3,0.0,0.0,41.5,0.0,55.4,89.5
0.0,"","15.06.2018 05:38",26.3,0.0,0.0,41.4,0.0,54.7,90.1
0.0,"","15.06.2018 05:37",26.3,0.0,0.0,41.4,0.0,54.7,90.1
0.0,"","15.06.2018 05:36",26.3,0.0,0.0,41.4,0.0,54.7,90.1
0.0,"","15.06.2018 05:35",26.3,0.0,0.0,41.4,0.0,54.7,90.1
0.0,"","15.06.2018 05:34",26.3,0.0,0.0,41.4,0.0,54.7,90.1
0.0,"","12.06.2018 05:40",26.4,0.0,0.0,41.4,0.0,54.6,90.3
0.0,"","12.06.2018 05:39",26.4,0.0,0.0,41.4,0.0,54.6,90.3
0.0,"","12.06.2018 05:38",26.4,0.0,0.0,41.4,0.0,54.6,90.3
0.0,"","12.06.2018 05:37",26.4,0.0,0.0,41.4,0.0,54.6,90.3
0.0,"","12.06.2018 05:36",26.4,0.0,0.0,41.4,0.0,54.6,90.3
0.0,"","10.06.2018 04:26",22.3,0.0,0.0,41.3,0.0,57.3,90.8
0.0,"","10.06.2018 04:25",22.3,0.0,0.0,41.3,0.0,57.3,90.8
0.0,"","10.06.2018 04:24",22.3,0.0,0.0,41.3,0.0,57.3,90.8
0.0,"","10.06.2018 04:23",22.3,0.0,0.0,41.3,0.0,57.3,90.8
0.0,"","10.06.2018 04:22",22.3,0.0,0.0,41.3,0.0,57.3,90.8
0.0,"","07.06.2018 10:21",22.6,0.0,0.0,41.4,0.0,57.1,90.0
0.0,"","07.06.2018 10:20",22.6,0.0,0.0,41.4,0.0,57.1,90.0
0.0,"","07.06.2018 10:19",22.6,0.0,0.0,41.4,0.0,57.1,90.0
0.0,"","07.06.2018 10:18",22.6,0.0,0.0,41.4,0.0,57.1,90.0
0.0,"","07.06.2018 10:17",22.6,0.0,0.0,41.4,0.0,57.1,90.0
0.0,"","06.06.2018 06:40",21.6,0.0,0.0,41.3,0.0,57.8,91.0
0.0,"","06.06.2018 06:39",21.6,0.0,0.0,41.3,0.0,57.8,91.0
0.0,"","06.06.2018 06:38",21.6,0.0,0.0,41.3,0.0,57.8,91.0
0.0,"","06.06.2018 06:37",21.6,0.0,0.0,41.3,0.0,57.8,91.0
0.0,"","06.06.2018 06:36",21.6,0.0,0.0,41.3,0.0,57.8,91.0
0.0,"","05.06.2018 07:01",21.7,0.0,0.0,41.2,0.0,57.7,91.6
0.0,"","05.06.2018 07:00",21.7,0.0,0.0,41.2,0.0,57.7,91.6
0.0,"","05.06.2018 06:59",21.7,0.0,0.0,41.2,0.0,57.7,91.6
0.0,"","05.06.2018 06:58",21.7,0.0,0.0,41.2,0.0,57.7,91.6
0.0,"","05.06.2018 06:57",21.7,0.0,0.0,41.2,0.0,57.7,91.6
0.0,"","04.06.2018 06:39",23.5,0.0,0.0,41.4,0.0,56.5,90.4
0.0,"","04.06.2018 06:38",23.5,0.0,0.0,41.4,0.0,56.5,90.4
0.0,"","04.06.2018 06:37",23.5,0.0,0.0,41.4,0.0,56.5,90.4
0.0,"","04.06.2018 06:36",23.5,0.0,0.0,41.4,0.0,56.5,90.4
0.0,"","04.06.2018 06:35",23.5,0.0,0.0,41.4,0.0,56.5,90.4
0.0,"","25.05.2018 10:29",21.6,0.0,0.0,41.5,0.0,57.8,89.5
0.0,"","25.05.2018 10:28",21.6,0.0,0.0,41.5,0.0,57.8,89.5
0.0,"","25.05.2018 10:27",21.6,0.0,0.0,41.5,0.0,57.8,89.5
0.0,"","25.05.2018 10:26",21.6,0.0,0.0,41.5,0.0,57.8,89.5
0.0,"","25.05.2018 10:25",21.6,0.0,0.0,41.5,0.0,57.8,89.5
0.0,"","17.05.2018 09:59",21.9,0.0,0.0,41.0,0.0,57.6,92.5
0.0,"","17.05.2018 09:58",21.9,0.0,0.0,41.0,0.0,57.6,92.5
0.0,"","17.05.2018 09:57",21.9,0.0,0.0,41.0,0.0,57.6,92.5
0.0,"","17.05.2018 09:56",21.9,0.0,0.0,41.0,0.0,57.6,92.5
0.0,"","17.05.2018 09:55",21.9,0.0,0.0,41.0,0.0,57.6,92.5
0.0,"","09.05.2018 09:34",21.6,0.0,0.0,41.6,0.0,57.8,89.0
0.0,"","09.05.2018 09:33",21.6,0.0,0.0,41.6,0.0,57.8,89.0
0.0,"","09.05.2018 09:32",21.6,0.0,0.0,41.6,0.0,57.8,89.0
0.0,"","09.05.2018 09:31",21.6,0.0,0.0,41.6,0.0,57.8,89.0
0.0,"","09.05.2018 09:30",21.6,0.0,0.0,41.6,0.0,57.8,89.0
0.0,"","29.04.2018 08:29",21.0,0.0,0.0,41.4,0.0,58.2,89.2
0.0,"","29.04.2018 08:28",21.0,0.0,0.0,41.4,0.0,58.2,89.2
0.0,"","29.04.2018 08:27",21.0,0.0,0.0,41.4,0.0,58.2,89.2
0.0,"","29.04.2018 08:26",21.0,0.0,0.0,41.4,0.0,58.2,89.2
0.0,"","29.04.2018 08:25",21.0,0.0,0.0,41.4,0.0,58.2,89.2
0.0,"","13.04.2018 04:58",32.7,0.0,0.0,41.9,0.0,50.6,87.6
0.0,"","13.04.2018 04:57",32.7,0.0,0.0,41.9,0.0,50.6,87.6
0.0,"","13.04.2018 04:56",32.7,0.0,0.0,41.9,0.0,50.6,87.6
0.0,"","13.04.2018 04:55",32.7,0.0,0.0,41.9,0.0,50.6,87.6
0.0,"","13.04.2018 04:54",32.7,0.0,0.0,41.9,0.0,50.6,87.6
0.0,"","11.04.2018 07:45",20.9,0.0,0.0,42.0,0.0,58.3,86.8
0.0,"","11.04.2018 07:44",20.9,0.0,0.0,42.0,0.0,58.3,86.8
0.0,"","11.04.2018 07:43",20.9,0.0,0.0,42.0,0.0,58.3,86.8
0.0,"","11.04.2018 07:42",20.9,0.0,0.0,42.0,0.0,58.3,86.8
0.0,"","11.04.2018 07:41",20.9,0.0,0.0,42.0,0.0,58.3,86.8
0.0,"","10.04.2018 05:31",24.0,0.0,0.0,42.1,0.0,56.3,86.4
0.0,"","10.04.2018 05:30",24.0,0.0,0.0,42.1,0.0,56.3,86.4
0.0,"","10.04.2018 05:29",24.0,0.0,0.0,42.1,0.0,56.3,86.4
0.0,"","10.04.2018 05:28",24.0,0.0,0.0,42.1,0.0,56.3,86.4
0.0,"","10.04.2018 05:27",24.0,0.0,0.0,42.1,0.0,56.3,86.4
0.0,"","06.04.2018 06:49",24.4,0.0,0.0,41.9,0.0,56.0,87.6
0.0,"","06.04.2018 06:48",24.4,0.0,0.0,41.9,0.0,56.0,87.6
0.0,"","06.04.2018 06:47",24.4,0.0,0.0,41.9,0.0,56.0,87.6
0.0,"","06.04.2018 06:46",24.4,0.0,0.0,41.9,0.0,56.0,87.6
0.0,"","06.04.2018 06:45",24.4,0.0,0.0,41.9,0.0,56.0,87.6
0.0,"","01.04.2018 05:07",25.6,0.0,0.0,41.7,0.0,55.2,88.6
0.0,"","01.04.2018 05:06",25.6,0.0,0.0,41.7,0.0,55.2,88.6
0.0,"","01.04.2018 05:05",25.6,0.0,0.0,41.7,0.0,55.2,88.6
0.0,"","01.04.2018 05:04",25.6,0.0,0.0,41.7,0.0,55.2,88.6
0.0,"","01.04.2018 05:03",25.6,0.0,0.0,41.7,0.0,55.2,88.6
0.0,"","28.03.2018 07:10",23.5,0.0,0.0,42.2,0.0,56.6,87.1
0.0,"","28.03.2018 07:09",23.5,0.0,0.0,42.2,0.0,56.6,87.1
0.0,"","28.03.2018 07:08",23.5,0.0,0.0,42.2,0.0,56.6,87.1
0.0,"","28.03.2018 07:07",23.5,0.0,0.0,42.2,0.0,56.6,87.1
0.0,"","28.03.2018 07:06",23.5,0.0,0.0,42.2,0.0,56.6,87.1
0.0,"","21.03.2018 18:25",20.7,0.0,0.0,42.0,0.0,58.5,88.1
0.0,"","21.03.2018 18:24",20.7,0.0,0.0,42.0,0.0,58.5,88.1
0.0,"","21.03.2018 18:23",20.7,0.0,0.0,42.0,0.0,58.5,88.1
0.0,"","21.03.2018 18:22",20.7,0.0,0.0,42.0,0.0,58.5,88.1
0.0,"","21.03.2018 18:21",20.7,0.0,0.0,42.0,0.0,58.5,88.1
0.0,"","15.03.2018 21:00",22.6,0.0,0.0,41.6,0.0,57.1,90.3
0.0,"","15.03.2018 20:59",22.6,0.0,0.0,41.6,0.0,57.1,90.3
0.0,"","15.03.2018 20:58",22.6,0.0,0.0,41.6,0.0,57.1,90.3
0.0,"","15.03.2018 20:57",22.6,0.0,0.0,41.6,0.0,57.1,90.3
0.0,"","15.03.2018 20:56",22.6,0.0,0.0,41.6,0.0,57.1,90.3
0.0,"","14.03.2018 07:41",25.3,0.0,0.0,42.1,0.0,55.5,87.2
0.0,"","14.03.2018 07:40",25.3,0.0,0.0,42.1,0.0,55.5,87.2
0.0,"","14.03.2018 07:39",25.3,0.0,0.0,42.1,0.0,55.5,87.2
0.0,"","14.03.2018 07:38",25.3,0.0,0.0,42.1,0.0,55.5,87.2
0.0,"","14.03.2018 07:37",25.3,0.0,0.0,42.1,0.0,55.5,87.2
0.0,"","13.03.2018 06:15",27.4,0.0,0.0,42.4,0.0,54.1,85.6
0.0,"","13.03.2018 06:14",27.4,0.0,0.0,42.4,0.0,54.1,85.6
0.0,"","13.03.2018 06:13",27.4,0.0,0.0,42.4,0.0,54.1,85.6
0.0,"","13.03.2018 06:12",27.4,0.0,0.0,42.4,0.0,54.1,85.6
0.0,"","13.03.2018 06:11",27.4,0.0,0.0,42.4,0.0,54.1,85.6
0.0,"","17.02.2018 10:36",20.6,0.0,0.0,42.2,0.0,58.5,86.6
0.0,"","17.02.2018 10:35",20.6,0.0,0.0,42.2,0.0,58.5,86.6
0.0,"","17.02.2018 10:34",20.6,0.0,0.0,42.2,0.0,58.5,86.6
0.0,"","17.02.2018 10:33",20.6,0.0,0.0,42.2,0.0,58.5,86.6
0.0,"","17.02.2018 10:32",20.6,0.0,0.0,42.2,0.0,58.5,86.6
0.0,"","16.02.2018 08:03",27.6,0.0,0.0,42.1,0.0,53.9,87.5
0.0,"","16.02.2018 08:02",27.6,0.0,0.0,42.1,0.0,53.9,87.5
0.0,"","16.02.2018 08:01",27.6,0.0,0.0,42.1,0.0,53.9,87.5
0.0,"","16.02.2018 08:00",27.6,0.0,0.0,42.1,0.0,53.9,87.5
0.0,"","16.02.2018 07:59",27.6,0.0,0.0,42.1,0.0,53.9,87.5
0.0,"","15.02.2018 10:42",23.4,0.0,0.0,42.3,0.0,56.7,86.4
0.0,"","15.02.2018 10:41",23.4,0.0,0.0,42.3,0.0,56.7,86.4
0.0,"","15.02.2018 10:40",23.4,0.0,0.0,42.3,0.0,56.7,86.4
0.0,"","15.02.2018 10:39",23.4,0.0,0.0,42.3,0.0,56.7,86.4
0.0,"","15.02.2018 10:38",23.4,0.0,0.0,42.3,0.0,56.7,86.4
0.0,"","14.02.2018 09:22",20.5,0.0,0.0,42.1,0.0,58.6,87.5
0.0,"","14.02.2018 09:21",20.5,0.0,0.0,42.1,0.0,58.6,87.5
0.0,"","14.02.2018 09:20",20.5,0.0,0.0,42.1,0.0,58.6,87.5
0.0,"","14.02.2018 09:19",20.5,0.0,0.0,42.1,0.0,58.6,87.5
0.0,"","14.02.2018 09:18",20.5,0.0,0.0,42.1,0.0,58.6,87.5
0.0,"","09.02.2018 22:38",15.232022,0.0,0.0,42.5,0.0,51.406094,85.69999
0.0,"","08.02.2018 07:09",26.6,0.0,0.0,42.4,0.0,54.6,85.5
0.0,"","08.02.2018 07:08",26.6,0.0,0.0,42.4,0.0,54.6,85.5
0.0,"","08.02.2018 07:07",26.6,0.0,0.0,42.4,0.0,54.6,85.5
0.0,"","08.02.2018 07:06",26.6,0.0,0.0,42.4,0.0,54.6,85.5
0.0,"","08.02.2018 07:05",26.6,0.0,0.0,42.4,0.0,54.6,85.5
0.0,"","06.02.2018 06:13",30.3,0.0,0.0,42.4,0.0,52.2,85.8
0.0,"","06.02.2018 06:12",30.3,0.0,0.0,42.4,0.0,52.2,85.8
0.0,"","06.02.2018 06:11",30.3,0.0,0.0,42.4,0.0,52.2,85.8
0.0,"","06.02.2018 06:10",30.3,0.0,0.0,42.4,0.0,52.2,85.8
0.0,"","06.02.2018 06:09",30.3,0.0,0.0,42.4,0.0,52.2,85.8
0.0,"","05.02.2018 06:20",31.2,0.0,0.0,42.3,0.0,51.6,86.5
0.0,"","05.02.2018 06:19",31.2,0.0,0.0,42.3,0.0,51.6,86.5
0.0,"","05.02.2018 06:18",31.2,0.0,0.0,42.3,0.0,51.6,86.5
0.0,"","05.02.2018 06:17",31.2,0.0,0.0,42.3,0.0,51.6,86.5
0.0,"","05.02.2018 06:16",31.2,0.0,0.0,42.3,0.0,51.6,86.5
0.0,"","04.02.2018 06:14",28.3,0.0,0.0,42.2,0.0,53.5,86.7
0.0,"","04.02.2018 06:13",28.3,0.0,0.0,42.2,0.0,53.5,86.7
0.0,"","04.02.2018 06:12",28.3,0.0,0.0,42.2,0.0,53.5,86.7
0.0,"","04.02.2018 06:11",28.3,0.0,0.0,42.2,0.0,53.5,86.7
0.0,"","04.02.2018 06:10",28.3,0.0,0.0,42.2,0.0,53.5,86.7
0.0,"","01.02.2018 09:03",22.2,0.0,0.0,42.1,0.0,57.5,87.4
0.0,"","01.02.2018 09:02",22.2,0.0,0.0,42.1,0.0,57.5,87.4
0.0,"","01.02.2018 09:01",22.2,0.0,0.0,42.1,0.0,57.5,87.4
0.0,"","01.02.2018 09:00",22.2,0.0,0.0,42.1,0.0,57.5,87.4
0.0,"","01.02.2018 08:59",22.2,0.0,0.0,42.1,0.0,57.5,87.4
0.0,"","24.01.2018 09:59",24.1,0.0,0.0,42.5,0.0,56.2,85.1
0.0,"","24.01.2018 09:58",24.1,0.0,0.0,42.5,0.0,56.2,85.1
0.0,"","24.01.2018 09:57",24.1,0.0,0.0,42.5,0.0,56.2,85.1
0.0,"","24.01.2018 09:56",24.1,0.0,0.0,42.5,0.0,56.2,85.1
0.0,"","24.01.2018 09:55",24.1,0.0,0.0,42.5,0.0,56.2,85.1
15.2,"","23.01.2018 23:33",23.4,0.0,0.0,39.1,0.0,55.999996,102.30001
15.2,"","20.01.2018 22:59",23.7,0.0,0.0,39.0,0.0,55.7,103.2
0.0,"","18.01.2018 11:15",20.1,0.0,0.0,42.3,0.0,58.9,86.1
0.0,"","18.01.2018 11:14",20.1,0.0,0.0,42.3,0.0,58.9,86.1
0.0,"","18.01.2018 11:13",20.1,0.0,0.0,42.3,0.0,58.9,86.1
0.0,"","18.01.2018 11:12",20.1,0.0,0.0,42.3,0.0,58.9,86.1
0.0,"","18.01.2018 11:11",20.1,0.0,0.0,42.3,0.0,58.9,86.1
15.1,"","14.01.2018 23:31",23.3,0.0,0.0,39.1,0.0,56.1,102.0
0.0,"","14.01.2018 06:15",26.3,0.0,0.0,42.2,0.0,54.8,86.9
0.0,"","14.01.2018 06:14",26.3,0.0,0.0,42.2,0.0,54.8,86.9
0.0,"","14.01.2018 06:13",26.3,0.0,0.0,42.2,0.0,54.8,86.9
0.0,"","14.01.2018 06:12",26.3,0.0,0.0,42.2,0.0,54.8,86.9
0.0,"","14.01.2018 06:11",26.3,0.0,0.0,42.2,0.0,54.8,86.9
0.0,"","07.01.2018 07:12",20.3,0.0,0.0,42.4,0.0,58.7,85.6
0.0,"","07.01.2018 07:11",20.3,0.0,0.0,42.4,0.0,58.7,85.6
0.0,"","07.01.2018 07:10",20.3,0.0,0.0,42.4,0.0,58.7,85.6
0.0,"","07.01.2018 07:09",20.3,0.0,0.0,42.4,0.0,58.7,85.6
0.0,"","07.01.2018 07:08",20.3,0.0,0.0,42.4,0.0,58.7,85.6
0.0,"","06.01.2018 10:38",19.7,0.0,0.0,42.4,0.0,59.1,85.5
0.0,"","06.01.2018 10:37",19.7,0.0,0.0,42.4,0.0,59.1,85.5
0.0,"","06.01.2018 10:36",19.7,0.0,0.0,42.4,0.0,59.1,85.5
0.0,"","06.01.2018 10:35",19.7,0.0,0.0,42.4,0.0,59.1,85.5
0.0,"","06.01.2018 10:34",19.7,0.0,0.0,42.4,0.0,59.1,85.5
0.0,"","05.01.2018 08:29",26.1,0.0,0.0,42.4,0.0,54.9,85.6
0.0,"","05.01.2018 08:28",26.1,0.0,0.0,42.4,0.0,54.9,85.6
0.0,"","05.01.2018 08:27",26.1,0.0,0.0,42.4,0.0,54.9,85.6
0.0,"","05.01.2018 08:26",26.1,0.0,0.0,42.4,0.0,54.9,85.6
0.0,"","05.01.2018 08:25",26.1,0.0,0.0,42.4,0.0,54.9,85.6
15.1,"","05.01.2018 00:26",23.3,0.0,0.0,39.1,0.0,56.1,102.0
0.0,"","02.01.2018 18:10",19.8,0.0,0.0,42.3,0.0,59.1,86.3
0.0,"","02.01.2018 18:09",19.8,0.0,0.0,42.3,0.0,59.1,86.3
0.0,"","02.01.2018 18:08",19.8,0.0,0.0,42.3,0.0,59.1,86.3
0.0,"","02.01.2018 18:07",19.8,0.0,0.0,42.3,0.0,59.1,86.3
0.0,"","02.01.2018 18:06",19.8,0.0,0.0,42.3,0.0,59.1,86.3
15.1,"","30.12.2017 00:27",23.1,0.0,0.0,39.2,0.0,56.2,101.9
15.1,"","20.12.2017 21:08",23.0,0.0,0.0,39.3,0.0,56.3,101.4
14.8,"","06.12.2017 21:13",22.6,0.0,0.0,39.5,0.0,56.6,100.5
14.9,"","29.11.2017 22:27",22.8,0.0,0.0,39.5,0.0,56.5,100.9
14.9,"","26.11.2017 09:47",22.9,0.0,0.0,39.4,0.0,56.3,101.2
15.1,"","15.11.2017 22:15",23.5,0.0,0.0,39.1,0.0,55.9,102.9
15.1,"","12.11.2017 23:09",23.8,0.0,0.0,39.0,0.0,55.7,103.6
15.2,"","06.11.2017 22:34",24.0,0.0,0.0,38.9,0.0,55.6,104.0
15.0,"","23.10.2017 21:46",23.4,0.0,0.0,39.2,0.0,56.0,102.6
15.0,"","13.10.2017 20:19",23.4,0.0,0.0,39.2,0.0,56.0,102.6
15.1,"","09.10.2017 20:33",23.4,0.0,0.0,39.2,0.0,56.0,102.7

**Comment by oliexdev** [comment] 2018-02-24 15:33
thx should be fixed with commit https://github.com/oliexdev/openScale/commit/6854b9704e93c862657f99528077de203f21525c
After refactoring this class the regression line was not probably calculated because the time was not set and I fixed also some other side effects.

**Closed by oliexdev** 2018-02-24 15:33 UTC
Labels: bug
