### ISSUE TITLE
[Bug] IllegalArgumentException

### ISSUE THREAD

**Issue by LoHub** [oliexdev/openScale#1075] opened 2024-09-29 21:30 UTC
**Describe the bug**

I encounter a crash when I change the number of days to average over in trendline settings to 2. I can not reproduce the bug and it may not related.

**To Reproduce**

I can not reproduce the bug

**Expected behavior**

No crash.

**Additional context**

A crash append.

**Debug log**

```
Build version: 2.5.2 
Build date: 1981-01-01 01:01:02 
Current date: 2024-09-29 20:37:31 
Device: Google Pixel 8 
OS version: Android 14 (SDK 34) 
 
Stack trace:  
java.lang.IllegalArgumentException: Navigation action/destination com.health.openscale:id/action_nav_main_preferences_to_nav_graph_preferences cannot be found from the current destination Destination(com.health.openscale:id/nav_graph_preferences) label=Chart class=com.health.openscale.gui.preferences.GraphPreferences
	at androidx.navigation.NavController.navigate(NavController.kt:1663)
	at androidx.navigation.NavController.navigate(NavController.kt:1595)
	at androidx.navigation.NavController.navigate(NavController.kt:2130)
	at com.health.openscale.gui.preferences.MainPreferences$4.onPreferenceClick(MainPreferences.java:83)
	at androidx.preference.Preference.performClick(Preference.java:1200)
	at androidx.preference.Preference.performClick(Preference.java:1182)
	at androidx.preference.Preference$1.onClick(Preference.java:182)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by oliexdev** [comment] 2024-11-17 11:54
I cannot reproduce it either, I will close it when it happen again please reopen it.

**Closed by oliexdev** 2024-11-17 11:54 UTC
Labels: bug
