### ISSUE TITLE
My Scale2, invalid percentage with muscle and some bad view 

### ISSUE THREAD

**Issue by laltroweb** [oliexdev/openScale#885] opened 2022-09-25 11:47 UTC
Like from screen: numbers are not full readable and muscle percentage is crazy 😅
![Screenshot_20220925-134503_openScale](https://user-images.githubusercontent.com/16841896/192141759-5203ad9f-2074-43ab-955b-1a648c85f818.png)

**Comment by misibacsi** [comment] 2022-10-26 05:19
![Screenshot_20221026_065748](https://user-images.githubusercontent.com/11352049/197940981-64b8f156-aeef-4824-ab3d-ca03c03a02a3.jpg)

I have similar comment, but my problem is with the false colors in the muscle line (see picture).

**Comment by oliexdev** [comment] 2022-12-08 13:32
Do you have multiply measurements on the same day? For the muscle percent please try out the latest dev version

**Comment by oliexdev** [comment] 2022-12-08 15:13
Yes, please do a backup of your data before you install the dev version (use CSV export and do in the settings Backup -> Export Backup)

**Comment by misibacsi** [comment] 2022-12-11 14:56
Hello

I already uninstalled the current software and installed the "dev" version.
(Older data are lost, but this is not important now).

Although the sw version remained the same: 2.4.6 (61)

The problem with the "muscle" is not the percent, but the colored scale.

The colors have a meaning, if I am not mistaken, blue: too low, green:
normal, red: too much.

In case of muscle the software shows green between 20-24 kg, but in reality
it is "too low". The "too low" upper border is near 50 kg. 50+ kg is the
"normal" value.
But in the software the colored line ends near 50 kg (and does not show
bigger numbers).

I send you 2 screenshots: 1 your sw, the other is Mi Body 2 image.
I guess the Mi scale shows the correct values.

Pay attention to values of "muscle" and the scale.

I hope you understand the problem and will correct it.

Regards

OliE ***@***.***> ezt írta (időpont: 2022. dec. 8., Cs 16:13):

**Comment by Focshole** [comment] 2022-12-19 16:42
About the bad muscle data, i think it is a duplicate of #787

**Closed** 2023-01-20 16:15 UTC
Labels: duplicate, question
