### ISSUE TITLE
Too dark icons/text in dark mode

### ISSUE THREAD

**Issue by naoliv** [oliexdev/openScale#611] opened 2020-08-15 20:43 UTC
**Describe the bug**
With the new dark theme some elements are difficult to read sometimes, specially when they are in black color (icons and text):

![](https://user-images.githubusercontent.com/982338/90321285-a47eae80-df1e-11ea-8fe6-8bd7b066eea3.png)
![](https://user-images.githubusercontent.com/982338/90321287-a6487200-df1e-11ea-9071-0474f6452d2b.png)
![](https://user-images.githubusercontent.com/982338/90321288-a7799f00-df1e-11ea-8909-12d166f387ce.png)
![](https://user-images.githubusercontent.com/982338/90321290-a8aacc00-df1e-11ea-8d24-a9b6573ac99f.png)
![](https://user-images.githubusercontent.com/982338/90321291-a9436280-df1e-11ea-8624-6ea121ace058.png)

**Expected behavior**
Black icons/texts should probably be lighter (gray or white).

**Comment by oliexdev** [comment] 2020-08-16 05:54
which openScale version and which Android version do you using?

**Comment by naoliv** [comment] 2020-08-16 06:09
Oh, sorry.
It's openScale `2.3.1-light` with Android 10.

**Comment by oliexdev** [comment] 2020-08-16 06:16
Unfortunately, I can't reproduce this behaviour!? Did you enable the dark mode in the openScale settings? Did you enable the Night mode globally in Android?

**Comment by oliexdev** [comment] 2020-08-16 06:17
Do you have some special theme installed on your smartphone?

**Comment by naoliv** [comment] 2020-08-16 06:27
Yes, dark mode is enabled globally in Android.
In openScale it's saying that it's using the `Light` theme

![](https://user-images.githubusercontent.com/982338/90328126-5d210e00-df70-11ea-9a4c-0a503c340d92.png)

**Comment by naoliv** [comment] 2020-08-16 06:32
I didn't change anything in openScale theme, but maybe it should follow the global Android setting? (regarding the dark mode)
By forcing `Dark` now in openScale the objects are properly changed to a light theme.

**Comment by oliexdev** [comment] 2020-08-16 06:32
Thanks now I can reproduce this error. For the moment you can switch it to the dark mode in openScale that would fix that problem but I need to fix this bug

**Comment by oliexdev** [comment] 2020-08-16 06:46
should be fixed now

**Closed by oliexdev** 2020-08-16 06:46 UTC
Labels: bug
