### ISSUE TITLE
Crash when rotating screen in BT settings

### ISSUE THREAD

**Issue by mhaas** [oliexdev/openScale#884] opened 2022-09-23 05:29 UTC
**Describe the bug**

When I rotate my phone to landscape mode in the BT settings, the app crashes.

**To Reproduce**
1. Go to BT settings
2. Rotate phone to landscape mode 

Reproduced with [latest dev version](https://github.com/oliexdev/openScale/releases/tag/travis-dev-build): no

**Expected behavior**
No crash.

**Additional context**

The text in the bt settings is cut off in portait mode, that is why i flipped the phone 

**Debug log**
Attach a debug log (see Settings -> About -> Save debug log to file) that is captured while reproducing the issue.
Build version: 2.4.6-pro 
Build date: 1981-01-01 01:01:02 
Current date: 2022-09-23 07:25:05 
Device: Samsung SM-G991B 
OS version: Android 12 (SDK 31) 
 
Stack trace:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.health.openscale.pro/com.health.openscale.gui.MainActivity}: android.view.InflateException: Binary XML file line #34 in com.health.openscale.pro:layout/activity_main: Binary XML file line #34 in com.health.openscale.pro:layout/activity_main: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4111)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6429)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6294)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: android.view.InflateException: Binary XML file line #34 in com.health.openscale.pro:layout/activity_main: Binary XML file line #34 in com.health.openscale.pro:layout/activity_main: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #34 in com.health.openscale.pro:layout/activity_main: Error inflating class fragment
Caused by: java.lang.IllegalArgumentException: ID does not reference a View inside this Activity
	at android.app.Activity.requireViewById(Activity.java:3496)
	at androidx.core.app.ActivityCompat.requireViewById(ActivityCompat.java:368)
	at androidx.navigation.Navigation.findNavController(Navigation.kt:48)
	at com.health.openscale.gui.preferences.BluetoothPreferences.onCreateView(BluetoothPreferences.java:82)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2777)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3020)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:295)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:274)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1073)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1001)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:965)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1127)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1130)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1088)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:485)
	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:706)
	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
	at com.health.openscale.gui.MainActivity.onCreate(MainActivity.java:172)
	at android.app.Activity.performCreate(Activity.java:8290)
	at android.app.Activity.performCreate(Activity.java:8270)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4085)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4277)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:6429)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:6294)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:71)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8751)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by marclaporte** [comment] 2022-11-12 06:13
Duplicate of https://github.com/oliexdev/openScale/issues/889

**Closed** 2022-12-08 13:26 UTC
Labels: duplicate
